In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
# !unzip '/content/drive/MyDrive/All Over the Workover.zip'

In [3]:
import pandas as pd

public_train=pd.read_csv('/content/All Over the Workover/public_train.csv')
print(public_train.shape)
public_train.head()

(1734579, 17)

   pump_id Well_Number  ... Pump_Torque.1  PUMP_ID_PHASE
0      NaN      AGB001  ...           NaN            1.0
1      NaN      AGB001  ...           NaN            1.0
2      NaN      AGB001  ...           NaN            1.0
3      NaN      AGB001  ...           NaN            1.0
4      NaN      AGB001  ...           NaN            1.0

[5 rows x 17 columns]

In [4]:
public_train=public_train.dropna(subset=['PUMP_ID_PHASE'])
print(public_train.shape)

(1117926, 17)

In [5]:
import numpy as np

public_train['Gas_Capacity_Rate']=np.where(public_train['Gas_Rate']!=0,public_train['Gas_Capacity']/public_train['Gas_Rate'],np.NaN)
public_train['Water_Capacity_Rate']=np.where(public_train['Water_Rate']!=0,public_train['Water_Capacity']/public_train['Water_Rate'],np.NaN)
public_train['Gas_Pump_Pressure']=np.where(public_train['Pump_Pressure']!=0,public_train['Gas_Pressure']/public_train['Pump_Pressure'],np.NaN)
public_train['Pump_Pressure_Speed']=np.where(public_train['Pump_Speed']!=0,public_train['Pump_Pressure']/public_train['Pump_Speed'],np.NaN)

In [6]:
public_train['Difference_actual_pred_gas']    = public_train['Gas_Capacity']-public_train['Gas_Rate']
public_train['Difference_actual_pred_water']  = public_train['Water_Capacity']-public_train['Water_Rate']
public_train['Difference_bw_outer_inner']     = public_train['Gas_Pressure']-public_train['Pump_Pressure']

In [7]:
base=public_train[['pump_id','Well_Number','Date','PUMP_ID_PHASE','HR','Volumetric_Capacity']].dropna()

public_train_mean=public_train.groupby('PUMP_ID_PHASE').mean()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]
                  
public_train_mean.reset_index(inplace=True)
public_train_mean_cols=['PUMP_ID_PHASE']
for col in public_train_mean.columns:
  if col!='PUMP_ID_PHASE':
    public_train_mean_cols.append(col+"_mean")

public_train_mean.columns=public_train_mean_cols

public_train_nunique=public_train.groupby('PUMP_ID_PHASE').nunique()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]
                  
public_train_nunique.reset_index(inplace=True)
public_train_nunique_cols=['PUMP_ID_PHASE']
for col in public_train_nunique.columns:
  if col!='PUMP_ID_PHASE':
    public_train_nunique_cols.append(col+"_nunique")

public_train_nunique.columns=public_train_nunique_cols

public_train_min=public_train.groupby('PUMP_ID_PHASE').min()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

public_train_min.reset_index(inplace=True)
public_train_min_cols=['PUMP_ID_PHASE']
for col in public_train_min.columns:
  if col!='PUMP_ID_PHASE':
    public_train_min_cols.append(col+"_min")

public_train_min.columns=public_train_min_cols

public_train_max=public_train.groupby('PUMP_ID_PHASE').max()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

public_train_max.reset_index(inplace=True)
public_train_max_cols=['PUMP_ID_PHASE']
for col in public_train_max.columns:
  if col!='PUMP_ID_PHASE':
    public_train_max_cols.append(col+"_max")

public_train_max.columns=public_train_max_cols

public_train_std=public_train.groupby('PUMP_ID_PHASE').std()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

public_train_std.reset_index(inplace=True)
public_train_std_cols=['PUMP_ID_PHASE']
for col in public_train_std.columns:
    if col!='PUMP_ID_PHASE':
      public_train_std_cols.append(col+"_std")

public_train_std.columns=public_train_std_cols

public_train_skew=public_train.groupby('PUMP_ID_PHASE').skew()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

public_train_skew.reset_index(inplace=True)
public_train_skew_cols=['PUMP_ID_PHASE']
for col in public_train_skew.columns:
  if col!='PUMP_ID_PHASE':
    public_train_skew_cols.append(col+"_skew")

public_train_skew.columns=public_train_skew_cols

public_train_wellnumber_mean=public_train.groupby('Well_Number').mean()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

public_train_wellnumber_mean.reset_index(inplace=True)
public_train_wellnumber_mean_cols=['Well_Number']
for col in public_train_wellnumber_mean.columns:
  if col!='Well_Number':
    public_train_wellnumber_mean_cols.append(col+"_wellnumber_mean")

public_train_wellnumber_mean.columns=public_train_wellnumber_mean_cols

public_train_wellnumber_nunique=public_train.groupby('Well_Number').nunique()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

public_train_wellnumber_nunique.reset_index(inplace=True)
public_train_wellnumber_nunique_cols=['Well_Number']
for col in public_train_wellnumber_nunique.columns:
  if col!='Well_Number':
    public_train_wellnumber_nunique_cols.append(col+"_wellnumber_nunique")

public_train_wellnumber_nunique.columns=public_train_wellnumber_nunique_cols

public_train_wellnumber_min=public_train.groupby('Well_Number').min()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]


public_train_wellnumber_min.reset_index(inplace=True)
public_train_wellnumber_min_cols=['Well_Number']
for col in public_train_wellnumber_min.columns:
  if col!='Well_Number':
    public_train_wellnumber_min_cols.append(col+"_wellnumber_min")

public_train_wellnumber_min.columns=public_train_wellnumber_min_cols

public_train_wellnumber_max=public_train.groupby('Well_Number').max()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

public_train_wellnumber_max.reset_index(inplace=True)
public_train_wellnumber_max_cols=['Well_Number']
for col in public_train_wellnumber_max.columns:
  if col!='Well_Number':
    public_train_wellnumber_max_cols.append(col+"_wellnumber_max")

public_train_wellnumber_max.columns=public_train_wellnumber_max_cols

public_train_wellnumber_std=public_train.groupby('Well_Number').std()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

public_train_wellnumber_std.reset_index(inplace=True)
public_train_wellnumber_std_cols=['Well_Number']
for col in public_train_wellnumber_std.columns:
    if col!='Well_Number':
      public_train_wellnumber_std_cols.append(col+"_wellnumber_std")

public_train_wellnumber_std.columns=public_train_wellnumber_std_cols

public_train_wellnumber_skew=public_train.groupby('Well_Number').skew()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

public_train_wellnumber_skew.reset_index(inplace=True)
public_train_wellnumber_skew_cols=['Well_Number']
for col in public_train_wellnumber_skew.columns:
  if col!='Well_Number':
    public_train_wellnumber_skew_cols.append(col+"_wellnumber_skew")

public_train_wellnumber_skew.columns=public_train_wellnumber_skew_cols


base=base.merge(public_train_mean,how='left',on='PUMP_ID_PHASE')\
    .merge(public_train_min,how='left',on='PUMP_ID_PHASE')\
    .merge(public_train_nunique,how='left',on='PUMP_ID_PHASE')\
    .merge(public_train_max,how='left',on='PUMP_ID_PHASE')\
    .merge(public_train_std,how='left',on='PUMP_ID_PHASE')\
    .merge(public_train_skew,how='left',on='PUMP_ID_PHASE')\
    .merge(public_train_wellnumber_mean,how='left',on='Well_Number')\
    .merge(public_train_wellnumber_min,how='left',on='Well_Number')\
    .merge(public_train_wellnumber_nunique,how='left',on='Well_Number')\
    .merge(public_train_wellnumber_max,how='left',on='Well_Number')\
    .merge(public_train_wellnumber_std,how='left',on='Well_Number')\
    .merge(public_train_wellnumber_skew,how='left',on='Well_Number')

base

      pump_id  ... Difference_bw_outer_inner_wellnumber_skew
0         1.0  ...                                 -4.596325
1         3.0  ...                                  1.215346
2         5.0  ...                                  1.063432
3         7.0  ...                                  0.597150
4        11.0  ...                                 -0.538911
...       ...  ...                                       ...
1774   3740.0  ...                                  0.788803
1775   3741.0  ...                                  0.788803
1776   3746.0  ...                                  6.584122
1777   3747.0  ...                                  6.584122
1778   3749.0  ...                                  0.134442

[1779 rows x 222 columns]

In [8]:
well_details=pd.read_csv('/content/All Over the Workover/well_details.csv')
print(well_details.shape)
well_details.head()

(1231, 6)

  Well_Number                              Completion_Type  ...   Depth  Casing_Diam
0      AGB001  VERTICAL PRE-PERFORATED (SWELLABLE PACKERS)  ...  832.04        6.336
1      AGB002                                VERTICAL FRAC  ...  847.00        4.892
2      AGB003                                VERTICAL FRAC  ...  825.00        4.892
3      AGB004                                VERTICAL FRAC  ...  826.00        4.892
4      AGB005                                VERTICAL FRAC  ...  815.50        4.892

[5 rows x 6 columns]

In [9]:
base=base.merge(well_details,how='left',on='Well_Number')
base

      pump_id Well_Number        Date  ...  Bottom_Perforation   Depth  Casing_Diam
0         1.0      AGB001  2020-06-25  ...              777.44  832.04        6.336
1         3.0      AGB002  2020-07-28  ...              815.69  847.00        4.892
2         5.0      AGB003  2020-07-27  ...              800.61  825.00        4.892
3         7.0      AGB004  2020-06-14  ...              791.61  826.00        4.892
4        11.0      AGB006  2020-09-07  ...              795.27  829.00        4.892
...       ...         ...         ...  ...                 ...     ...          ...
1774   3740.0      ZUP206  2019-06-29  ...              778.81  818.13        6.336
1775   3741.0      ZUP206  2020-03-16  ...              778.81  818.13        6.336
1776   3746.0      ZUP208  2019-10-30  ...              698.64     NaN        6.336
1777   3747.0      ZUP208  2020-07-04  ...              698.64     NaN        6.336
1778   3749.0      ZUP209  2020-11-05  ...              913.16  931.38        4.892

[1779 rows x 227 columns]

In [10]:
intake_depth=pd.read_csv("/content/intake_depth v2.csv")
print(intake_depth.shape)
intake_depth.head()

(3752, 4)

  Well_Number  Intake_Depth Tubing_Run_Date Tubing_Pull_Date
0      AGB001        803.30       6/09/2018       25/06/2020
1      AGB001        805.27      25/06/2020              NaN
2      AGB002        793.14       4/03/2019       28/07/2020
3      AGB002        818.53      28/07/2020              NaN
4      AGB003        770.10      19/03/2019       26/07/2020

In [11]:
intake_depth=intake_depth.dropna(subset=['Tubing_Pull_Date'])
intake_depth.shape

(2552, 4)

In [12]:
mean_Intake_depth=pd.DataFrame(intake_depth.groupby('Well_Number',as_index=False).mean()[['Well_Number','Intake_Depth']])
mean_Intake_depth.columns=['Well_Number','Mean_Intake_Depth']
min_Intake_depth=pd.DataFrame(intake_depth.groupby('Well_Number',as_index=False).min()[['Well_Number','Intake_Depth']])
min_Intake_depth.columns=['Well_Number','Min_Intake_Depth']
max_Intake_depth=pd.DataFrame(intake_depth.groupby('Well_Number',as_index=False).max()[['Well_Number','Intake_Depth']])
max_Intake_depth.columns=['Well_Number','Max_Intake_Depth']
# skew_Intake_depth=pd.DataFrame(intake_depth.groupby('Well_Number',as_index=False).skew()[['Well_Number','Intake_Depth']])
# skew_Intake_depth.columns=['Well_Number','Skew_Intake_Depth']
std_Intake_depth=pd.DataFrame(intake_depth.groupby('Well_Number',as_index=False).std()[['Well_Number','Intake_Depth']])
std_Intake_depth.columns=['Well_Number','Std_Intake_Depth']
# median_Intake_depth=pd.DataFrame(intake_depth.groupby('Well_Number',as_index=False).median())
# median_Intake_depth.columns=['Well_Number','Median_Intake_Depth']


base=base.merge(mean_Intake_depth,how='left',on='Well_Number')
base=base.merge(min_Intake_depth,how='left',on='Well_Number')
base=base.merge(max_Intake_depth,how='left',on='Well_Number')
# base=base.merge(skew_Intake_depth,how='left',on='Well_Number')
base=base.merge(std_Intake_depth,how='left',on='Well_Number')
# base=base.merge(median_Intake_depth,how='left',on='Well_Number')
base

      pump_id Well_Number  ... Max_Intake_Depth  Std_Intake_Depth
0         1.0      AGB001  ...           803.30               NaN
1         3.0      AGB002  ...           793.14               NaN
2         5.0      AGB003  ...           770.10               NaN
3         7.0      AGB004  ...           755.46               NaN
4        11.0      AGB006  ...           760.48               NaN
...       ...         ...  ...              ...               ...
1774   3740.0      ZUP206  ...           785.89          3.118341
1775   3741.0      ZUP206  ...           785.89          3.118341
1776   3746.0      ZUP208  ...           705.01          2.467803
1777   3747.0      ZUP208  ...           705.01          2.467803
1778   3749.0      ZUP209  ...           894.39               NaN

[1779 rows x 231 columns]

In [13]:
private_input=pd.read_csv('/content/All Over the Workover/private_input.csv')
print(private_input.shape)
private_input.head()

(726517, 15)

   pump_id Well_Number  ... Pump_Torque.1  PUMP_ID_PHASE
0      NaN      AGB005  ...           NaN            9.0
1      NaN      AGB005  ...           NaN            9.0
2      NaN      AGB005  ...           NaN            9.0
3      NaN      AGB005  ...           NaN            9.0
4      NaN      AGB005  ...           NaN            9.0

[5 rows x 15 columns]

In [14]:
private_input=private_input.dropna(subset=['PUMP_ID_PHASE'])
print(private_input.shape)

(477424, 15)

In [15]:
import numpy as np
private_input['Gas_Capacity_Rate']=np.where(private_input['Gas_Rate']!=0,private_input['Gas_Capacity']/private_input['Gas_Rate'],np.NaN)
private_input['Water_Capacity_Rate']=np.where(private_input['Water_Rate']!=0,private_input['Water_Capacity']/private_input['Water_Rate'],np.NaN)
private_input['Gas_Pump_Pressure']=np.where(private_input['Pump_Pressure']!=0,private_input['Gas_Pressure']/private_input['Pump_Pressure'],np.NaN)
private_input['Pump_Pressure_Speed']=np.where(private_input['Pump_Speed']!=0,private_input['Pump_Pressure']/private_input['Pump_Speed'],np.NaN)


private_input['Difference_actual_pred_gas']    = private_input['Gas_Capacity']-private_input['Gas_Rate']
private_input['Difference_actual_pred_water']  = private_input['Water_Capacity']-private_input['Water_Rate']
private_input['Difference_bw_outer_inner']     = private_input['Gas_Pressure']-private_input['Pump_Pressure']

In [16]:
base_test=private_input[['pump_id','Well_Number','Date','PUMP_ID_PHASE']].dropna()

private_input_mean=private_input.groupby('PUMP_ID_PHASE').mean()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

private_input_mean.reset_index(inplace=True)
private_input_mean_cols=['PUMP_ID_PHASE']
for col in private_input_mean.columns:
  if col!='PUMP_ID_PHASE':
    private_input_mean_cols.append(col+"_mean")

private_input_mean.columns=private_input_mean_cols

private_input_nunique=private_input.groupby('PUMP_ID_PHASE').nunique()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

private_input_nunique.reset_index(inplace=True)
private_input_nunique_cols=['PUMP_ID_PHASE']
for col in private_input_nunique.columns:
  if col!='PUMP_ID_PHASE':
    private_input_nunique_cols.append(col+"_nunique")

private_input_nunique.columns=private_input_nunique_cols

private_input_min=private_input.groupby('PUMP_ID_PHASE').min()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

private_input_min.reset_index(inplace=True)
private_input_min_cols=['PUMP_ID_PHASE']
for col in private_input_min.columns:
  if col!='PUMP_ID_PHASE':
    private_input_min_cols.append(col+"_min")

private_input_min.columns=private_input_min_cols

private_input_max=private_input.groupby('PUMP_ID_PHASE').max()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

private_input_max.reset_index(inplace=True)
private_input_max_cols=['PUMP_ID_PHASE']
for col in private_input_max.columns:
  if col!='PUMP_ID_PHASE':
    private_input_max_cols.append(col+"_max")

private_input_max.columns=private_input_max_cols

private_input_std=private_input.groupby('PUMP_ID_PHASE').std()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

private_input_std.reset_index(inplace=True)
private_input_std_cols=['PUMP_ID_PHASE']
for col in private_input_std.columns:
    if col!='PUMP_ID_PHASE':
      private_input_std_cols.append(col+"_std")

private_input_std.columns=private_input_std_cols

private_input_skew=private_input.groupby('PUMP_ID_PHASE').skew()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

private_input_skew.reset_index(inplace=True)
private_input_skew_cols=['PUMP_ID_PHASE']
for col in private_input_skew.columns:
  if col!='PUMP_ID_PHASE':
    private_input_skew_cols.append(col+"_skew")

private_input_skew.columns=private_input_skew_cols

private_input_wellnumber_mean=private_input.groupby('Well_Number').mean()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

private_input_wellnumber_mean.reset_index(inplace=True)
private_input_wellnumber_mean_cols=['Well_Number']
for col in private_input_wellnumber_mean.columns:
  if col!='Well_Number':
    private_input_wellnumber_mean_cols.append(col+"_wellnumber_mean")

private_input_wellnumber_mean.columns=private_input_wellnumber_mean_cols

private_input_wellnumber_nunique=private_input.groupby('Well_Number').nunique()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]
                  
private_input_wellnumber_nunique.reset_index(inplace=True)
private_input_wellnumber_nunique_cols=['Well_Number']
for col in private_input_wellnumber_nunique.columns:
  if col!='Well_Number':
    private_input_wellnumber_nunique_cols.append(col+"_wellnumber_nunique")

private_input_wellnumber_nunique.columns=private_input_wellnumber_nunique_cols

private_input_wellnumber_min=private_input.groupby('Well_Number').min()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

private_input_wellnumber_min.reset_index(inplace=True)
private_input_wellnumber_min_cols=['Well_Number']
for col in private_input_wellnumber_min.columns:
  if col!='Well_Number':
    private_input_wellnumber_min_cols.append(col+"_wellnumber_min")

private_input_wellnumber_min.columns=private_input_wellnumber_min_cols

private_input_wellnumber_max=private_input.groupby('Well_Number').max()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

private_input_wellnumber_max.reset_index(inplace=True)
private_input_wellnumber_max_cols=['Well_Number']
for col in private_input_wellnumber_max.columns:
  if col!='Well_Number':
    private_input_wellnumber_max_cols.append(col+"_wellnumber_max")

private_input_wellnumber_max.columns=private_input_wellnumber_max_cols

private_input_wellnumber_std=private_input.groupby('Well_Number').std()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

private_input_wellnumber_std.reset_index(inplace=True)
private_input_wellnumber_std_cols=['Well_Number']
for col in private_input_wellnumber_std.columns:
    if col!='Well_Number':
      private_input_wellnumber_std_cols.append(col+"_wellnumber_std")

private_input_wellnumber_std.columns=private_input_wellnumber_std_cols

private_input_wellnumber_skew=private_input.groupby('Well_Number').skew()[['Gas_Rate', 'Water_Rate', 'Gas_Capacity', 'Water_Capacity',
                  'Gas_Pressure', 'Pump_Pressure', 'Pump_Speed', 'Pump_Torque',
                  'Pump_Volumetric_Eff', 'Downhole_Gauge_Fluid_Level_Above_Sensor',
                  'Pump_Torque.1','Gas_Capacity_Rate','Water_Capacity_Rate','Gas_Pump_Pressure','Pump_Pressure_Speed',
                  'Difference_actual_pred_gas','Difference_actual_pred_water','Difference_bw_outer_inner']]

private_input_wellnumber_skew.reset_index(inplace=True)
private_input_wellnumber_skew_cols=['Well_Number']
for col in private_input_wellnumber_skew.columns:
  if col!='Well_Number':
    private_input_wellnumber_skew_cols.append(col+"_wellnumber_skew")

private_input_wellnumber_skew.columns=private_input_wellnumber_skew_cols


base_test=base_test.merge(private_input_mean,how='left',on='PUMP_ID_PHASE')\
    .merge(private_input_min,how='left',on='PUMP_ID_PHASE')\
    .merge(private_input_nunique,how='left',on='PUMP_ID_PHASE')\
    .merge(private_input_max,how='left',on='PUMP_ID_PHASE')\
    .merge(private_input_std,how='left',on='PUMP_ID_PHASE')\
    .merge(private_input_skew,how='left',on='PUMP_ID_PHASE')\
    .merge(private_input_wellnumber_mean,how='left',on='Well_Number')\
    .merge(private_input_wellnumber_min,how='left',on='Well_Number')\
    .merge(private_input_wellnumber_nunique,how='left',on='Well_Number')\
    .merge(private_input_wellnumber_max,how='left',on='Well_Number')\
    .merge(private_input_wellnumber_std,how='left',on='Well_Number')\
    .merge(private_input_wellnumber_skew,how='left',on='Well_Number')

base_test

     pump_id  ... Difference_bw_outer_inner_wellnumber_skew
0        9.0  ...                                 -1.527915
1       13.0  ...                                  3.505923
2       14.0  ...                                  3.505923
3       33.0  ...                                  2.792059
4       34.0  ...                                  2.792059
..       ...  ...                                       ...
814   3720.0  ...                                 13.231192
815   3730.0  ...                                 -1.116680
816   3743.0  ...                                  6.543494
817   3744.0  ...                                  6.543494
818   3751.0  ...                                 -0.078342

[819 rows x 220 columns]

In [17]:
base_test=base_test.merge(well_details,how='left',on='Well_Number')
base_test.head()

   pump_id Well_Number        Date  ...  Bottom_Perforation   Depth  Casing_Diam
0      9.0      AGB005  2020-07-05  ...              783.35  815.50        4.892
1     13.0      AGQ001  2017-12-10  ...              711.11  745.24        6.366
2     14.0      AGQ001  2019-06-17  ...              711.11  745.24        6.366
3     33.0      AGQ007  2017-05-07  ...              746.08  779.78        6.366
4     34.0      AGQ007  2020-05-09  ...              746.08  779.78        6.366

[5 rows x 225 columns]

In [18]:
base_test=base_test.merge(mean_Intake_depth,how='left',on='Well_Number')
base_test=base_test.merge(min_Intake_depth,how='left',on='Well_Number')
base_test=base_test.merge(max_Intake_depth,how='left',on='Well_Number')
# base_test=base_test.merge(skew_Intake_depth,how='left',on='Well_Number')
base_test=base_test.merge(std_Intake_depth,how='left',on='Well_Number')
base_test

     pump_id Well_Number  ... Max_Intake_Depth  Std_Intake_Depth
0        9.0      AGB005  ...       758.310000               NaN
1       13.0      AGQ001  ...       724.830017          9.142903
2       14.0      AGQ001  ...       724.830017          9.142903
3       33.0      AGQ007  ...       762.040000          8.032733
4       34.0      AGQ007  ...       762.040000          8.032733
..       ...         ...  ...              ...               ...
814   3720.0      ZUP197  ...       764.800000               NaN
815   3730.0      ZUP201  ...       824.180000               NaN
816   3743.0      ZUP207  ...       825.450000          1.195010
817   3744.0      ZUP207  ...       825.450000          1.195010
818   3751.0      ZUP210  ...       901.390000               NaN

[819 rows x 229 columns]

In [33]:
cols=[col for col in base.columns if col not in ['pump_id','Well_Number','Date','HR','Volumetric_Capacity','Completion_Type','PUMP_ID_PHASE'] ]
a=base[cols].isnull().sum()/base.shape[0]
cols=a[a<=0.6].index.tolist()

train_df = base[cols].copy()
test_df  = base_test[cols].copy()

base.HR=base.HR.astype(int)
target_y = base.HR.values

In [23]:
# !pip install catboost

In [34]:
from sklearn.model_selection import train_test_split
import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostClassifier
from sklearn.metrics import f1_score

## Model 1 :- Classification

In [36]:
train = train_df.copy()
test  = test_df.copy()

X_train, X_test, y_train, y_test = train_test_split(train, target_y,stratify= target_y, test_size=0.1, random_state=42)

model=xgb.XGBClassifier(random_state=42,scale_pos_weight=4,n_estimators=100,max_depth=4,colsample_bytree=1,learning_rate=0.1)
model.fit(X_train.fillna(999),y_train)

print(f1_score(y_test,model.predict_proba(X_test.fillna(999))[:,1]>0.5))

oof_pred1 = model.predict_proba(train.fillna(999))[:,1]
y_pred1 = model.predict_proba(test.fillna(999))[:,1]

0.5283018867924528

## Model 2 :- Classification

In [37]:
train = train_df.copy()
test  = test_df.copy()

X_train, X_test, y_train, y_test = train_test_split(train, target_y,stratify= target_y, test_size=0.1, random_state=42)

model=lgb.LGBMClassifier(random_state=42,scale_pos_weight=4,n_estimators=100,max_depth=4)

model.fit(X_train.fillna(999),y_train)

print(f1_score(y_test,model.predict_proba(X_test.fillna(999))[:,1]>0.5))

oof_pred2 = model.predict_proba(train.fillna(999))[:,1]
y_pred2 = model.predict_proba(test.fillna(999))[:,1]

0.4482758620689655

## Model 3

In [38]:
train = train_df.copy()
test  = test_df.copy()

X_train, X_test, y_train, y_test = train_test_split(train, target_y,stratify= target_y, test_size=0.1, random_state=42)

model=CatBoostClassifier(random_state=42,scale_pos_weight=4,verbose=0)

model.fit(X_train.fillna(999),y_train)

print(f1_score(y_test,model.predict_proba(X_test.fillna(999))[:,1]>0.5))

oof_pred3 = model.predict_proba(train.fillna(999))[:,1]
y_pred3 = model.predict_proba(test.fillna(999))[:,1]

0.4583333333333333

## Model 4

In [39]:
train = train_df.copy()
test  = test_df.copy()

X_train, X_test, y_train, y_test = train_test_split(train, target_y,stratify= target_y, test_size=0.1, random_state=42)

model=xgb.XGBClassifier(random_state=42,scale_pos_weight=5,n_estimators=100,max_depth=4,colsample_bytree=1,learning_rate=0.1)

model.fit(X_train.fillna(999),y_train)

print(f1_score(y_test,model.predict_proba(X_test.fillna(999))[:,1]>0.5))

oof_pred4 = model.predict_proba(train.fillna(999))[:,1]
y_pred4 = model.predict_proba(test.fillna(999))[:,1]

0.4727272727272727

## Model 5

In [40]:
train = train_df.copy()
test  = test_df.copy()

X_train, X_test, y_train, y_test = train_test_split(train, target_y,stratify= target_y, test_size=0.1, random_state=42)

model=lgb.LGBMClassifier(random_state=42,scale_pos_weight=4,n_estimators=100)

model.fit(X_train.fillna(999),y_train)

print(f1_score(y_test,model.predict_proba(X_test.fillna(999))[:,1]>0.5))

oof_pred5 = model.predict_proba(train.fillna(999))[:,1]
y_pred5 = model.predict_proba(test.fillna(999))[:,1]

0.40909090909090906

## Model 6

In [43]:
train = train_df.copy()
test  = test_df.copy()

X_train, X_test, y_train, y_test = train_test_split(train, target_y,stratify= target_y, test_size=0.1, random_state=42)

model=CatBoostClassifier(random_state=42,scale_pos_weight=3,verbose=0)

model.fit(X_train.fillna(999),y_train)

print(f1_score(y_test,model.predict_proba(X_test.fillna(999))[:,1]>0.5))

oof_pred6 = model.predict_proba(train.fillna(999))[:,1]
y_pred6 = model.predict_proba(test.fillna(999))[:,1]

0.4444444444444444

## Model 7

In [44]:
train = train_df.copy()
test  = test_df.copy()

X_train, X_test, y_train, y_test = train_test_split(train, target_y,stratify= target_y, test_size=0.1, random_state=42)

model=CatBoostClassifier(random_state=42,scale_pos_weight=5,verbose=0)

model.fit(X_train.fillna(999),y_train)

print(f1_score(y_test,model.predict_proba(X_test.fillna(999))[:,1]>0.5))

oof_pred7 = model.predict_proba(train.fillna(999))[:,1]
y_pred7 = model.predict_proba(test.fillna(999))[:,1]

0.4

In [45]:
meta_train_df = pd.DataFrame(target_y,columns = ['predictions'])

meta_train_df['model1'] = oof_pred1
meta_train_df['model2'] = oof_pred2
meta_train_df['model3'] = oof_pred3
meta_train_df['model4'] = oof_pred4
meta_train_df['model5'] = oof_pred5
meta_train_df['model6'] = oof_pred6
meta_train_df['model7'] = oof_pred7

meta_train_df

      predictions    model1    model2  ...    model5    model6    model7
0               0  0.025921  0.017024  ...  0.002419  0.022113  0.039834
1               0  0.008630  0.005695  ...  0.000160  0.010688  0.015409
2               0  0.015035  0.023959  ...  0.000196  0.029976  0.024749
3               0  0.126007  0.316524  ...  0.007834  0.035890  0.051413
4               0  0.026177  0.030545  ...  0.001311  0.028007  0.025068
...           ...       ...       ...  ...       ...       ...       ...
1774            0  0.059938  0.036328  ...  0.000510  0.096801  0.100971
1775            0  0.145131  0.056223  ...  0.006014  0.069943  0.086325
1776            0  0.112045  0.055993  ...  0.002067  0.074408  0.105099
1777            1  0.048689  0.018355  ...  0.001022  0.053258  0.114213
1778            0  0.222591  0.243197  ...  0.007747  0.154673  0.162053

[1779 rows x 8 columns]

In [46]:
meta_test_df = pd.DataFrame()
meta_test_df['model1'] = y_pred1
meta_test_df['model2'] = y_pred2
meta_test_df['model3'] = y_pred3
meta_test_df['model4'] = y_pred4
meta_test_df['model5'] = y_pred5
meta_test_df['model6'] = y_pred6
meta_test_df['model7'] = y_pred7

meta_test_df

       model1    model2    model3    model4    model5    model6    model7
0    0.023195  0.017988  0.029962  0.017032  0.000855  0.032651  0.038990
1    0.080390  0.041337  0.045478  0.065406  0.003521  0.036863  0.041295
2    0.221509  0.164414  0.133019  0.121306  0.005418  0.114999  0.133807
3    0.021022  0.084905  0.015920  0.029865  0.004592  0.022737  0.023462
4    0.355741  0.194454  0.149172  0.417002  0.016578  0.147325  0.140913
..        ...       ...       ...       ...       ...       ...       ...
814  0.162278  0.169104  0.161874  0.266293  0.004127  0.152791  0.180336
815  0.010827  0.004003  0.026487  0.010582  0.000147  0.026174  0.018337
816  0.171409  0.059154  0.201088  0.115476  0.009963  0.215236  0.215125
817  0.194731  0.143333  0.247211  0.188685  0.009614  0.234857  0.250201
818  0.321635  0.306720  0.402027  0.370647  0.029937  0.287505  0.378368

[819 rows x 7 columns]

In [76]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import *
from sklearn.metrics import *
train_df = meta_train_df
test_df  = meta_test_df


thresh    = 0.15
target_y  = train_df['predictions'].values
train_df  = train_df.drop(['predictions'],axis=1)

print(train_df.shape,test_df.shape)

train     = train_df.values
test      = test_df.values
train_y   = target_y

oof_pred               = np.zeros((len(train), ))
oof_pred_nearest       = np.zeros((len(train), ))
y_pred                 = np.zeros((len(test), ))
n_splits               = 20
kf                     = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

for fold, (tr_ind, val_ind) in enumerate(kf.split(train, train_y)):
  X_train, X_val     = train[tr_ind], train[val_ind]
  y_train, y_val     = train_y[tr_ind], train_y[val_ind]

  model  = LogisticRegression(random_state=42)
  
  model.fit(X_train,y_train)
  
  val_pred                  = model.predict_proba(X_val)[:,1]
  oof_pred[val_ind]         = val_pred

  

  val_preds = np.where(val_pred>thresh,1,0)
  print('F1:- ',f1_score(y_val,val_preds),' fold ',fold+1)
  print('recall:- ',recall_score(y_val,val_preds),' fold ',fold+1)
  print('Precision:- ',precision_score(y_val,val_preds),' fold ',fold+1)
  print('\n')
  
  y_pred += model.predict_proba(test)[:,1] / (n_splits)



oof_pred                 = np.where(oof_pred>thresh,1,0)
print('OOF f1(actual):- ',(f1_score(train_y,oof_pred)))

y_pred = np.where(y_pred>thresh,1,0)

(1779, 7) (819, 7)
F1:-  0.9230769230769231  fold  1
recall:-  0.9230769230769231  fold  1
Precision:-  0.9230769230769231  fold  1


F1:-  0.9600000000000001  fold  2
recall:-  0.9230769230769231  fold  2
Precision:-  1.0  fold  2


F1:-  0.9166666666666666  fold  3
recall:-  0.8461538461538461  fold  3
Precision:-  1.0  fold  3


F1:-  0.9600000000000001  fold  4
recall:-  0.9230769230769231  fold  4
Precision:-  1.0  fold  4


F1:-  0.8148148148148148  fold  5
recall:-  0.8461538461538461  fold  5
Precision:-  0.7857142857142857  fold  5


F1:-  0.962962962962963  fold  6
recall:-  1.0  fold  6
Precision:-  0.9285714285714286  fold  6


F1:-  0.9600000000000001  fold  7
recall:-  0.9230769230769231  fold  7
Precision:-  1.0  fold  7


F1:-  0.9285714285714286  fold  8
recall:-  1.0  fold  8
Precision:-  0.8666666666666667  fold  8


F1:-  0.9230769230769231  fold  9
recall:-  0.9230769230769231  fold  9
Precision:-  0.9230769230769231  fold  9


F1:-  0.962962962962963  fold  10
recall:-  1.0  fold  10
Precision:-  0.9285714285714286  fold  10


F1:-  0.9285714285714286  fold  11
recall:-  1.0  fold  11
Precision:-  0.8666666666666667  fold  11


F1:-  0.962962962962963  fold  12
recall:-  1.0  fold  12
Precision:-  0.9285714285714286  fold  12


F1:-  0.9600000000000001  fold  13
recall:-  0.9230769230769231  fold  13
Precision:-  1.0  fold  13


F1:-  0.9285714285714286  fold  14
recall:-  1.0  fold  14
Precision:-  0.8666666666666667  fold  14


F1:-  0.962962962962963  fold  15
recall:-  1.0  fold  15
Precision:-  0.9285714285714286  fold  15


F1:-  1.0  fold  16
recall:-  1.0  fold  16
Precision:-  1.0  fold  16


F1:-  0.888888888888889  fold  17
recall:-  0.9230769230769231  fold  17
Precision:-  0.8571428571428571  fold  17


F1:-  0.923076923076923  fold  18
recall:-  0.8571428571428571  fold  18
Precision:-  1.0  fold  18


F1:-  0.9655172413793104  fold  19
recall:-  1.0  fold  19
Precision:-  0.9333333333333333  fold  19


F1:-  1.0  fold  20
recall:-  1.0  fold  20
Precision:-  1.0  fold  20


OOF f1(actual):-  0.941398865784499

In [77]:
a = pd.DataFrame(y_pred,columns=['output'])
a.output.value_counts()/a.shape[0]

0    0.86569
1    0.13431
Name: output, dtype: float64

In [73]:
submission=pd.read_csv("/content/submission.csv")
submission.head()

   pump_id Well_Number        Date  Volumetric_Capacity     HR
0      9.0      AGB005  2020-07-05                  0.0  False
1     13.0      AGQ001  2017-12-10                  0.0  False
2     14.0      AGQ001  2019-06-17                  0.0  False
3     33.0      AGQ007  2017-05-07                  0.0  False
4     34.0      AGQ007  2020-05-09                  0.0  False

In [74]:
submission['HR']=y_pred
submission.HR.value_counts()/submission.shape[0]

0    0.846154
1    0.153846
Name: HR, dtype: float64

In [75]:
submission.to_csv("class_meta_logistic7models.csv",index=False)

In [ ]:
import lightgbm as lgb
# from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
cols=[col for col in base.columns if col not in ['pump_id','Well_Number','Date','HR','Volumetric_Capacity','Completion_Type','PUMP_ID_PHASE'] ]
a=base[cols].isnull().sum()/base.shape[0]
cols=a[a<=0.6].index.tolist()

base.HR=base.HR.astype(int)
X_train, X_test, y_train, y_test = train_test_split(base[cols], base['Volumetric_Capacity'], test_size=0.2, random_state=42)

# model=xgb.XGBRegressor(random_state=42,reg_lambda=4,n_estimators=100,max_depth=3,learning_rate=0.1)
model=lgb.LGBMRegressor(random_state=42,reg_lambda=3,n_estimators=100,learning_rate=0.1)
# model=CatBoostRegressor(random_state=42,verbose=0,learning_rate=0.08)
model.fit(X_train.fillna(0),y_train)

LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=42, reg_alpha=0.0, reg_lambda=3, silent=True,
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:
!pip install catboost

Collecting catboost
  Downloading https://files.pythonhosted.org/packages/96/3b/bb419654adcf7efff42ed8a3f84e50c8f236424b7ed1cc8ccd290852e003/catboost-0.24.4-cp37-none-manylinux1_x86_64.whl (65.7MB)
     |████████████████████████████████| 65.7MB 72kB/s
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.19.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (4.4.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.1.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (2.8.1)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (1.3.3)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Installing collected packages: catboost
Successfully installed catboost-0.24.4

In [ ]:
from catboost import CatBoostRegressor
train=base[cols].fillna(0).values
train_y=base['Volumetric_Capacity'].values
test=base_test[cols].fillna(0).values
import numpy as np
from sklearn.model_selection import *
from sklearn.metrics import mean_absolute_error


oof_pred               = np.zeros((len(train), ))
y_pred                 = np.zeros((len(test), ))
n_splits               = 20
kf=KFold(n_splits=n_splits, shuffle=True, random_state=42)

for fold, (tr_ind, val_ind) in enumerate(kf.split(train, train_y)):
  X_train, X_val     = train[tr_ind], train[val_ind]
  y_train, y_val     = train_y[tr_ind], train_y[val_ind]

  # model = lgb.LGBMRegressor(random_state=42,reg_lambda=4,n_estimators=70,learning_rate=0.1)
  # model = xgb.XGBRegressor(random_state=42,reg_lambda=5,n_estimators=90,learning_rate=0.1)
  model=CatBoostRegressor(random_state=42,verbose=0)
  model.fit(X_train,y_train)
  
  val_pred          = model.predict(X_val)
  oof_pred[val_ind] = val_pred

  print('MAE:- ',mean_absolute_error(y_val,val_pred),' fold ',fold)
  
  y_pred += model.predict(test) / (n_splits)



print('OOF MAE:- ',(mean_absolute_error(train_y,oof_pred)))

MAE:-  10.801697873107017  fold  0
MAE:-  11.441060653841221  fold  1
MAE:-  10.577462441408658  fold  2
MAE:-  10.931397106022818  fold  3
MAE:-  9.854414038787608  fold  4
MAE:-  8.266903990487206  fold  5
MAE:-  13.235192585931971  fold  6
MAE:-  10.499824016844324  fold  7
MAE:-  10.335927794529905  fold  8
MAE:-  11.61380141780914  fold  9
MAE:-  11.320332896601457  fold  10
MAE:-  11.899182935407902  fold  11
MAE:-  9.132295327046466  fold  12
MAE:-  11.00580194688285  fold  13
MAE:-  9.2361900963754  fold  14
MAE:-  9.647933640397023  fold  15
MAE:-  8.761899353754517  fold  16
MAE:-  9.31354829395029  fold  17
MAE:-  11.702071212958156  fold  18
MAE:-  10.694749307429554  fold  19
OOF MAE:-  10.513482511199893

In [ ]:
((10.20/12)*0.7)+(1-0.0.64)*0.3

0.7290490201711342

In [ ]:
((11.19465662867334/12)*0.7)+(1-0.5254237288135593)*0.3

0.7953945180285436

In [ ]:
submission['Volumetric_Capacity']=y_pred
submission.Volumetric_Capacity.describe()

count    819.000000
mean      38.785854
std       22.626376
min        8.207612
25%       23.024862
50%       32.719964
75%       48.183871
max      145.782278
Name: Volumetric_Capacity, dtype: float64

In [ ]:
submission.HR=submission.HR.astype(bool)
submission.to_csv("submission_lgbm_missingcut0.6_newdataadded_cbregressor.csv",index=False)

In [ ]:
submission.head()

   pump_id Well_Number        Date  Volumetric_Capacity     HR
0      9.0      AGB005  2020-07-05            34.181308  False
1     13.0      AGQ001  2017-12-10            17.822465  False
2     14.0      AGQ001  2019-06-17            15.167899  False
3     33.0      AGQ007  2017-05-07            20.009041  False
4     34.0      AGQ007  2020-05-09            20.724899  False

In [ ]:
submission.to_csv("only_class_0.64fscore.csv",index=False)